---

- name: Install nginx
  apt:
    name=nginx
    state=present

- name: nginx config
  template:
    src=default.conf.j2 dest=/etc/nginx/sites-available/default
    mode=644
    backup=yes
  notify: restart nginx

- name: nginx started
  service:
    name=nginx
    state=started
    enabled=yes


- name: nginx running
  command: /usr/sbin/service nginx status
