---

- hosts: all
  sudo: yes
  gather_facts: no

  vars:
    users:
      - name: steve
        sudoer: yes
        auth_key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6IMFOP2K/n2UbtP29d9hU1Ae9vkxpCtd87H7PX5xBfjsh1Tkvq3rRE+Jr6pzPja4gPRCikLm3fV3PdEp4eh1OaSP4SnuBFWcHOpxdDuU+pjNdGMBZlQqjzC0cxjAvW7ZtnT7YHYzH6zHr+t7Z8IESsnw7idDUCupr4Zqot7PaylnI4NLb1zQQxyD+XnjPRu8Ne/0JSyKizkCkXhUuYDbvRYFAs/jFm3pmurodrOx62cwVpdztsHiK5mdTwIQhObzSb3ZnDLNNfXO3yUcX9kWJ6eQ9iP5whw2OBddf+2EoCZtshYIqtGNYaFFdf8tGF5ZwugCHxe/gzlzDMVb9ZM49w== steve@dcn.org
      - name: kim
        sudoer: yes
        auth_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9jnh/9e38IzpuaFz35a/ddn5ilZifqgCk4/rsWyLQ2facSxOkAHW89bNNlnwILYyyKXoJP42h2HMmh+dTakrYeZl2dSAILScEkPJ2kQPYwQEHAH++fuYRE2uw6KShnB7siSPpjoF1Or6PrN5cnazViXbRdelxGEBBu+JZUUhD0l5DbCMWNh1QwQssaMY8dOFfkB32o/c6pZtMYiX8O8LhZsqgerLqfsVOqiC1IMbMZi89BXBKKe5tFGY1oFzBiJX9JfIpEaTZ8iw11XaA2Y36Gjt4O7WPswTbpmbfdYapf5cUPMDntSh2kZX6dzjkqAnIXTXyBX7C55uFyCkv+bFz kim@TKNMBP2.local

  pre_tasks:
    - name: Ensure plone_group
      group: name=plone_group

  roles:
    - create_users

  tasks:
    - name: Ensure plone_daemon
      user:
        name=plone_daemon
        group=plone_group
        shell=/bin/bash
        createhome=yes
        # generate_ssh_key=yes

    - name: Ensure plone_buildout
      user:
        name=plone_buildout
        group=plone_group
