---

- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: Enable ufw
    ufw: state=enabled policy=allow
  - name: Disable default in
    ufw: direction=incoming policy=deny
  - name: Allow ssh in
    ufw: rule=limit name=OpenSSH
  - name: 80 is open
    ufw: rule=allow port=80 proto=tcp
  - name: 443 is open
    ufw: rule=allow port=443 proto=tcp
  - name: 873 (rsyncd) is open to backup (rackspace internal network)
    ufw: rule=allow port=873 proto=tcp from_ip=10.177.1.141
  - name: 4949 (munin-node) is open to backup (rackspace internal network)
    ufw: rule=allow port=4949 proto=tcp from_ip=10.177.1.141


