---

# vars:
#   users:
#     - name: steve
#       sudoer: yes
#       auth_key: ssh-rsa ...


- name: Add users
  user:
    name={{ item.name }}
    system={{ item.sudoer }}
    shell=/bin/bash
    group={{ item.group  }}
  when: item.group is defined
  with_items: users

- name: Add users
  user:
    name={{ item.name }}
    system={{ item.sudoer }}
    shell=/bin/bash
  when: item.group is not defined
  with_items: users

- name: Add .ssh directories
  file:
    path=/home/{{ item.name }}/.ssh
    state=directory
    owner={{ item.name }}
  with_items: users

- name: Add keys
  lineinfile:
    dest=/home/{{ item.name }}/.ssh/authorized_keys
    state=present
    create=yes
    line="{{ item.auth_key }}"
    owner={{ item.name }}
  with_items: users

- name: Add to sudoers
  copy:
    dest: /etc/sudoers.d/{{ item.name }}
    content: |
             {{ item.name }}  ALL=(ALL) ALL
             {{ item.name }}  ALL=(plone_daemon, plone_buildout) NOPASSWD:ALL
             {{ item.name }}  ALL=(root) NOPASSWD:/usr/bin/supervisorctl
             #
  when: item.sudoer
  with_items: users

- name: SSH keys
  copy:
    src={{ item.keyfiles }}/
    dest=/home/{{ item.name }}/.ssh/
    owner={{ item.name }}
  when: item.keyfiles is defined
  with_items: users
