---

- name: Ensure unattended-upgrades
  apt: pkg={{ item }} state=present
  with_items:
    - unattended-upgrades
    - mailutils

- name: Turn on unattended unattended-upgrades
  lineinfile:
    dest=/etc/apt/apt.conf.d/10periodic
    line='APT::Periodic::Unattended-Upgrade "1";'
    state=present

- name: Turn on autoclean
  lineinfile:
    dest=/etc/apt/apt.conf.d/10periodic
    regexp='APT::Periodic::AutocleanInterval "0";'
    line='APT::Periodic::AutocleanInterval "7";'
    state=present

- name: Turn on autodownload
  lineinfile:
    dest=/etc/apt/apt.conf.d/10periodic
    regexp='APT::Periodic::Download-Upgradeable-Packages "0";'
    line='APT::Periodic::Download-Upgradeable-Packages "1";'
    state=present

- name: Turn on notification
  lineinfile:
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    regexp='//Unattended-Upgrade::Mail "root";'
    line='Unattended-Upgrade::Mail "root";'
    state=present

