supervisor_config_dir: "/etc/supervisor/conf.d/"
supervisorctl_command: "supervisorctl"
redirect_stderr: "false"
autorestart: "unexpected"
startsecs: 1
stopwaitsecs: 10
autostart: "true"
env_vars: {}
